#YAML file to specify configuration for Nginx deployment for pod J

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment_nginx_J
  labels:
    app: nginx_J
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx_J
  template:
    metadata:
      labels:
        app: nginx_J
    spec:
      containers:
      - name: nginx
        image: nginx:1.0
        ports:
        - containerPort: 80
    